"""create news url stock

Revision ID: 155d468173ca
Revises: b0010fc4bd74
Create Date: 2025-05-01 23:44:09.493740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '155d468173ca'
down_revision: Union[str, None] = 'b0010fc4bd74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('url_news', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'url_news')
    # ### end Alembic commands ###
