"""add_historical stock_data_table

Revision ID: cd855594244d
Revises: d973fe53ad20
Create Date: 2025-05-08 19:53:39.290466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd855594244d'
down_revision: Union[str, None] = 'd973fe53ad20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_stock_data',
    sa.Column('stock_id', sa.String(), nullable=False),
    sa.Column('trading_date', sa.DateTime(), nullable=False),
    sa.Column('variation', sa.String(length=20), nullable=False),
    sa.Column('min_price', sa.String(length=20), nullable=False),
    sa.Column('max_price', sa.String(length=20), nullable=False),
    sa.Column('volume', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_stock_data_stock_id'), 'historical_stock_data', ['stock_id'], unique=False)
    op.create_index(op.f('ix_historical_stock_data_trading_date'), 'historical_stock_data', ['trading_date'], unique=False)
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_index(op.f('ix_historical_stock_data_trading_date'), table_name='historical_stock_data')
    op.drop_index(op.f('ix_historical_stock_data_stock_id'), table_name='historical_stock_data')
    op.drop_table('historical_stock_data')
    # ### end Alembic commands ###
